services:
  bcferries-conditions-analytics:
    build:
      context: .
      args:
        - NEXT_PUBLIC_STRIPE_DONATION_URL=${NEXT_PUBLIC_STRIPE_DONATION_URL}
    restart: always
    env_file:
      - .env
    environment:
      - PGHOST=db
      - PGSSL=false
    volumes:
      - next_cache:/app/.next/cache
    depends_on:
      - db

  cron:
    build: ./cron
    restart: always
    env_file:
      - .env
    environment:
      - TZ=America/Vancouver
    volumes:
      - ~/backups/bcfca:/backups
    depends_on:
      - bcferries-conditions-analytics
      - db

  db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  next_cache:

networks:
  default:
    external: true
    name: proxy
